import { StyleSheet } from "react-native";

export const cameraViewfinderStyles = StyleSheet.create({
  container: {
    width: "100%",
    aspectRatio: 4 / 3,
    maxHeight: 440,
    backgroundColor: "#1A1A1A",
    borderRadius: 24,
    overflow: "hidden",
    position: "relative",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.16,
    shadowRadius: 14,
    elevation: 6,
  },
  cameraImage: {
    width: "100%",
    height: "100%",
  },
  guideBox: {
    position: "absolute",
    top: "8%",
    left: "8%",
    right: "8%",
    bottom: "8%",
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.5)",
  },
  cornerBracket: {
    position: "absolute",
    width: 28,
    height: 28,
    borderColor: "#F8EED4",
  },
  bracketTopLeft: {
    top: -3,
    left: -3,
    borderTopWidth: 5,
    borderLeftWidth: 5,
  },
  bracketTopRight: {
    top: -3,
    right: -3,
    borderTopWidth: 5,
    borderRightWidth: 5,
  },
  bracketBottomLeft: {
    bottom: -3,
    left: -3,
    borderBottomWidth: 5,
    borderLeftWidth: 5,
  },
  bracketBottomRight: {
    bottom: -3,
    right: -3,
    borderBottomWidth: 5,
    borderRightWidth: 5,
  },
  guidePill: {
    position: "absolute",
    bottom: 16,
    alignSelf: "center",
    backgroundColor: "rgba(36, 31, 39, 0.85)",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 999,
  },
  guidePillText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  liveOverlayBadge: {
    position: "absolute",
    top: 14,
    left: 14,
    backgroundColor: "rgba(36, 31, 39, 0.85)",
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
  },
  statusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  pulsingGreenDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#48BB78",
  },
  statusLiveText: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "700",
  },
  detectedRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  detectedText: {
    color: "#E2E8F0",
    fontSize: 12,
    fontWeight: "600",
  },
});
