import { StyleSheet } from "react-native";
import { theme } from "../../../../shared/constants/theme";

export const liveSigningStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
  },
  contentWrap: {
    width: "100%",
    maxWidth: 1240,
  },
  contentWrapTablet: {
    flex: 1,
    justifyContent: "space-between",
  },
  containerTablet: {
    paddingHorizontal: theme.spacing.md,
  },
  containerCompactTablet: {
    paddingVertical: 2,
  },
  pageHeading: {
    minHeight: 48,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing.md,
    marginBottom: theme.spacing.sm,
  },
  headingCopy: {
    flex: 1,
    minWidth: 0,
  },
  headingEyebrow: {
    color: theme.colors.primary,
    fontSize: 11,
    lineHeight: 15,
    fontWeight: "800",
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  pageTitle: {
    color: theme.colors.text,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "800",
  },
  pageTitleLarge: {
    fontSize: 29,
    lineHeight: 36,
  },
  privateBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 7,
    borderRadius: theme.radii.pill,
    backgroundColor: "#E8F3E9",
  },
  privateText: {
    color: theme.colors.success,
    fontSize: 12,
    fontWeight: "700",
  },
  workspace: {
    gap: theme.spacing.md,
  },
  workspaceTablet: {
    flex: 1,
    minHeight: 0,
    flexDirection: "row",
  },
  cameraPanel: {
    width: "100%",
    padding: theme.spacing.sm,
    borderRadius: 20,
    backgroundColor: "#351D4B",
  },
  cameraPanelTablet: {
    flex: 1.5,
    minWidth: 0,
    padding: theme.spacing.sm,
  },
  cameraPanelHeader: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing.sm,
    paddingHorizontal: theme.spacing.xs,
    paddingBottom: theme.spacing.xs,
  },
  cameraReadyLabel: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  cameraStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#D79A32",
  },
  cameraStatusLive: {
    backgroundColor: theme.colors.success,
  },
  cameraReadyText: {
    color: "#F8EED4",
    fontSize: 13,
    fontWeight: "700",
  },
  cameraSettingsButton: {
    minHeight: 38,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: theme.spacing.sm,
    borderRadius: theme.radii.control,
    borderWidth: 1,
    borderColor: "rgba(255, 248, 220, 0.28)",
  },
  cameraSettingsText: {
    color: "#F8EED4",
    fontSize: 13,
    fontWeight: "600",
  },
  cameraViewport: {
    width: "100%",
    aspectRatio: 16 / 10,
    minHeight: 220,
    maxHeight: 360,
    overflow: "hidden",
    position: "relative",
    borderRadius: 16,
    backgroundColor: "#21162B",
  },
  cameraViewportTablet: {
    flex: 1,
    minHeight: 0,
    maxHeight: 460,
    aspectRatio: undefined,
  },
  cameraFeed: {
    ...StyleSheet.absoluteFill,
  },
  cameraPlaceholder: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
    gap: theme.spacing.sm,
  },
  cameraPlaceholderText: {
    color: "#F8EED4",
    fontSize: 14,
    fontWeight: "600",
  },
  permissionFallback: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
    padding: theme.spacing.lg,
    backgroundColor: "#FFF8DC",
  },
  permissionIcon: {
    width: 52,
    height: 52,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 26,
    backgroundColor: "#F0E8F6",
  },
  permissionTitle: {
    marginTop: theme.spacing.sm,
    color: theme.colors.text,
    fontSize: 18,
    fontWeight: "800",
    textAlign: "center",
  },
  permissionBody: {
    maxWidth: 420,
    marginTop: 6,
    marginBottom: theme.spacing.sm,
    color: theme.colors.mutedText,
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
  cameraOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
  },
  guideFrame: {
    position: "absolute",
    top: "8%",
    left: "8%",
    right: "8%",
    bottom: "8%",
    borderWidth: 2,
    borderColor: "rgba(255, 248, 220, 0.58)",
    borderRadius: 18,
  },
  recognitionBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    borderRadius: theme.radii.pill,
    backgroundColor: "rgba(34, 22, 42, 0.76)",
  },
  recognitionText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "700",
  },
  cameraPrivacyBadge: {
    position: "absolute",
    left: theme.spacing.md,
    bottom: theme.spacing.md,
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 6,
    borderRadius: theme.radii.pill,
    backgroundColor: "rgba(34, 22, 42, 0.76)",
  },
  cameraPrivacyText: {
    color: "#FFFFFF",
    fontSize: 11,
    fontWeight: "700",
  },
  pausedOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(20, 15, 24, 0.54)",
  },
  pausedText: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "800",
  },
  controlsRow: {
    flexDirection: "row",
    gap: theme.spacing.xs,
    paddingTop: theme.spacing.sm,
  },
  controlBtn: {
    flex: 1,
  },
  conversationColumn: {
    gap: theme.spacing.sm,
  },
  conversationColumnTablet: {
    flex: 1,
    minWidth: 0,
  },
  messagePanel: {
    padding: theme.spacing.md,
    borderRadius: 18,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  translationPanel: {
    backgroundColor: "#FFFDF7",
  },
  staffPanel: {
    flex: 1,
    minHeight: 120,
  },
  panelLabelRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing.sm,
  },
  panelEyebrow: {
    color: theme.colors.primary,
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 1,
  },
  confirmedStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  reviewStatus: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
  },
  reviewStatusText: {
    color: theme.colors.success,
    fontSize: 11,
    fontWeight: "700",
  },
  confirmedText: {
    color: theme.colors.success,
    fontSize: 11,
    fontWeight: "700",
  },
  panelTitle: {
    marginTop: 5,
    color: theme.colors.text,
    fontSize: 17,
    lineHeight: 22,
    fontWeight: "800",
  },
  glossText: {
    marginTop: theme.spacing.sm,
    padding: theme.spacing.sm,
    borderRadius: 12,
    backgroundColor: "#F2EAF7",
    color: theme.colors.text,
    fontSize: 16,
    lineHeight: 23,
    fontWeight: "600",
  },
  glossTextLarge: {
    fontSize: 20,
    lineHeight: 28,
  },
  sendRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.xs,
    marginTop: theme.spacing.sm,
  },
  sendButton: {
    flex: 1,
  },
  editButton: {
    width: 44,
    height: 44,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.radii.control,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: theme.colors.surface,
  },
  pressed: {
    opacity: 0.78,
  },
  staffHeading: {
    flex: 1,
    minWidth: 0,
  },
  audioButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: theme.radii.control,
    borderWidth: 1,
    borderColor: theme.colors.border,
    backgroundColor: "#FFFDF7",
  },
  staffMessage: {
    marginTop: theme.spacing.md,
    padding: theme.spacing.sm,
    borderWidth: 1,
    borderColor: theme.colors.border,
    borderRadius: 12,
    color: theme.colors.mutedText,
    fontSize: 15,
    lineHeight: 22,
  },
  responseHint: {
    marginTop: theme.spacing.xs,
    color: theme.colors.mutedText,
    fontSize: 12,
    lineHeight: 17,
  },
});
