import { StyleSheet } from "react-native";
import { theme } from "../../../../shared/constants/theme";

export const tellerSelectionStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: theme.colors.background,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
  },
  content: {
    width: "100%",
    maxWidth: 820,
    alignSelf: "center",
  },
  intro: {
    alignItems: "center",
    marginBottom: theme.spacing.xl,
  },
  availabilityLabel: {
    minHeight: 32,
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
    paddingHorizontal: theme.spacing.md,
    borderRadius: theme.radii.pill,
    backgroundColor: "#E8F3E9",
  },
  availabilityDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: theme.colors.success,
  },
  availabilityText: {
    color: theme.colors.success,
    fontSize: 12,
    fontWeight: "800",
    letterSpacing: 0.8,
  },
  title: {
    marginTop: theme.spacing.sm,
    color: theme.colors.text,
    fontSize: 34,
    lineHeight: 42,
    fontWeight: "800",
    textAlign: "center",
  },
  titleLarge: {
    fontSize: 40,
    lineHeight: 48,
  },
  subtitle: {
    maxWidth: 560,
    marginTop: theme.spacing.xs,
    color: theme.colors.mutedText,
    fontSize: 17,
    lineHeight: 24,
    textAlign: "center",
  },
  subtitleLarge: {
    fontSize: 20,
    lineHeight: 28,
  },
  tellerList: {
    gap: theme.spacing.sm,
  },
  tellerOption: {
    minHeight: 110,
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.md,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
    borderWidth: 1.5,
    borderColor: theme.colors.border,
    borderRadius: 22,
    backgroundColor: theme.colors.surface,
    shadowColor: "#261B30",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 9,
    elevation: 2,
  },
  tellerOptionSelected: {
    borderWidth: 2,
    borderColor: theme.colors.primary,
    backgroundColor: "#F5EFFA",
    shadowColor: theme.colors.primary,
    shadowOpacity: 0.14,
    shadowRadius: 12,
    elevation: 4,
  },
  tellerOptionPressed: {
    opacity: 0.82,
    transform: [{ scale: 0.99 }],
  },
  avatar: {
    width: 70,
    height: 70,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 35,
    backgroundColor: "#F0E8F6",
  },
  avatarWithPhoto: {
    overflow: "hidden",
    backgroundColor: "transparent",
  },
  avatarPhotoSelected: {
    borderWidth: 3,
    borderColor: theme.colors.primary,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    borderRadius: 35,
  },
  avatarSelected: {
    backgroundColor: theme.colors.primary,
  },
  avatarText: {
    color: theme.colors.primary,
    fontSize: 18,
    fontWeight: "800",
  },
  avatarTextSelected: {
    color: "#FFFFFF",
  },
  tellerDetails: {
    flex: 1,
    minWidth: 0,
  },
  nameAndStatus: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: theme.spacing.sm,
  },
  tellerName: {
    flexShrink: 1,
    color: theme.colors.text,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: "800",
  },
  tellerNameLarge: {
    fontSize: 21,
    lineHeight: 28,
  },
  inlineAvailability: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexShrink: 0,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 5,
    borderRadius: theme.radii.pill,
    backgroundColor: "#E8F3E9",
  },
  inlineAvailabilityText: {
    color: theme.colors.success,
    fontSize: 12,
    fontWeight: "700",
  },
  tellerRole: {
    marginTop: 2,
    color: theme.colors.primary,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: "700",
  },
  tellerRoleLarge: {
    fontSize: 17,
    lineHeight: 22,
  },
  serviceDesk: {
    flex: 1,
    color: theme.colors.mutedText,
    fontSize: 13,
    lineHeight: 18,
  },
  serviceDeskRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
  },
  radio: {
    width: 25,
    height: 25,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 13,
    borderWidth: 2,
    borderColor: "#AAA2AF",
  },
  radioSelected: {
    borderColor: theme.colors.primary,
  },
  radioInner: {
    width: 13,
    height: 13,
    borderRadius: 7,
    backgroundColor: theme.colors.primary,
  },
  footer: {
    width: "100%",
    maxWidth: 820,
    alignSelf: "center",
    gap: theme.spacing.md,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.lg,
    backgroundColor: theme.colors.background,
  },
  footerTablet: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 0,
    paddingTop: theme.spacing.sm,
    paddingBottom: theme.spacing.md,
  },
  footerSelection: {
    minWidth: 0,
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: theme.spacing.sm,
  },
  footerSelectionMark: {
    width: 40,
    height: 40,
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    backgroundColor: "#F0E8F6",
  },
  footerSelectionMarkActive: {
    backgroundColor: theme.colors.primary,
  },
  footerSelectionCopy: {
    flex: 1,
    minWidth: 0,
  },
  footerSelectionTitle: {
    color: theme.colors.text,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "800",
  },
  connectButtonWrap: {
    width: "100%",
  },
  connectButtonWrapTablet: {
    width: 300,
    flexShrink: 0,
  },
  footerNote: {
    color: theme.colors.mutedText,
    fontSize: 12,
    lineHeight: 17,
  },
  statusBlock: {
    alignItems: "center",
    gap: 8,
    marginTop: 16,
    marginBottom: 8,
    paddingVertical: 20,
    paddingHorizontal: 16,
    borderRadius: theme.radii.panel,
    backgroundColor: theme.colors.surface,
    borderWidth: 1,
    borderColor: theme.colors.border,
  },
  statusTitle: {
    color: theme.colors.text,
    fontSize: 16,
    lineHeight: 22,
    fontWeight: "800",
    textAlign: "center",
  },
  statusText: {
    color: theme.colors.mutedText,
    fontSize: 14,
    lineHeight: 20,
    textAlign: "center",
  },
});