import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import {
  Accessibility, AlertTriangle, ArrowLeft, Building2, Camera, Check, ChevronRight,
  CircleHelp, Clock3, Hand, History, Keyboard, LayoutDashboard, Lock, MessageSquare,
  Mic, MonitorUp, Palette, Pause, Phone, Play, RefreshCw, RotateCcw, Send, Settings,
  ShieldCheck, SlidersHorizontal, Sparkles, Type, UserRound, Users, Volume2, WifiOff, X,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Switch } from "@/components/ui/switch";
import signingImage from "@/assets/kenyan-deaf-user-signing.jpg";
import staffImage from "@/assets/kenyan-staff-portrait.jpg";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Signova — Accessible Communication" },
      { name: "description", content: "A two-way sign-language communication experience for Kenyan service counters." },
      { property: "og:title", content: "Signova — Accessible Communication" },
      { property: "og:description", content: "A two-way sign-language communication experience for Kenyan service counters." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: SignovaApp,
});

type Mode = "deaf" | "staff" | "admin";
type Step = "splash" | "welcome" | "method" | "connecting" | "permission" | "ready" | "live" | "translating" | "confirm" | "sent" | "conversation" | "response" | "uncertain" | "offline" | "complete" | "settings" | "help" | "text";

const stepTitles: Record<Step, string> = {
  splash: "Signova", welcome: "Welcome", method: "Communication method", connecting: "Connecting",
  permission: "Camera access", ready: "Ready to sign", live: "Live recognition", translating: "Translation",
  confirm: "Confirm message", sent: "Message sent", conversation: "Conversation", response: "Staff response",
  uncertain: "Check translation", offline: "Connection interrupted", complete: "Complete", settings: "Accessibility",
  help: "Help", text: "Type a message",
};

function Logo({ compact = false }: { compact?: boolean }) {
  return <div className="flex items-center gap-3"><span className={`${compact ? "size-9" : "size-12"} grid shrink-0 place-items-center rounded-xl bg-primary text-primary-foreground`}><Hand aria-hidden="true" /></span><span className={`${compact ? "text-xl" : "text-3xl"} font-display font-extrabold text-primary`}>Signova</span></div>;
}

function SignovaApp() {
  const [mode, setMode] = useState<Mode>("deaf");
  return (
    <main className="min-h-dvh bg-background text-foreground">
      <nav aria-label="Choose product view" className="sticky top-0 z-50 border-b border-border bg-background/95 px-3 py-2 backdrop-blur sm:px-6">
        <div className="mx-auto grid max-w-7xl grid-cols-[auto_minmax(0,1fr)] items-center gap-3">
          <Logo compact />
          <div className="ml-auto flex min-w-0 items-center gap-1 rounded-xl bg-muted p-1" role="group" aria-label="Product views">
            {([['deaf','Deaf user',Hand],['staff','Staff',Users],['admin','Admin',Building2]] as const).map(([id,label,Icon]) => (
              <button key={id} onClick={() => setMode(id)} aria-label={`Open ${label} view`} aria-pressed={mode === id} className={`flex min-h-11 items-center gap-2 rounded-lg px-3 text-sm font-bold focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring/30 ${mode === id ? "bg-primary text-primary-foreground shadow-sm" : "text-muted-foreground hover:bg-card"}`}><Icon className="size-5" aria-hidden="true"/><span className="hidden sm:inline">{label}</span></button>
            ))}
          </div>
        </div>
      </nav>
      {mode === "deaf" ? <DeafApp /> : mode === "staff" ? <StaffDashboard /> : <AdminPortal />}
    </main>
  );
}

function DeafApp() {
  const [step, setStep] = useState<Step>("splash");
  const [largeText, setLargeText] = useState(false);
  useEffect(() => {
    if (step !== "splash") return undefined;
    const timer = window.setTimeout(() => setStep("welcome"), 1600);
    return () => window.clearTimeout(timer);
  }, [step]);
  return (
    <section aria-label="Deaf-user tablet application" className="mx-auto max-w-6xl px-3 py-5 sm:px-6 sm:py-8">
      <div className="mb-3 flex items-center justify-between gap-3 text-xs font-bold uppercase text-muted-foreground sm:mb-4">
        <span>Deaf-user app · Tablet first</span><span>{stepTitles[step]}</span>
      </div>
      <div className={`relative mx-auto min-h-[720px] max-w-5xl overflow-hidden rounded-[1.75rem] border-[10px] border-foreground bg-card shadow-2xl sm:min-h-[760px] ${largeText ? "text-[112%]" : ""}`}>
        <div className="flex h-8 items-center justify-between bg-foreground px-5 text-xs font-bold text-primary-foreground"><span>9:41</span><span className="flex items-center gap-2"><span className="size-2 rounded-full bg-chart-2"/>Secure session</span></div>
        {step !== "splash" && <TabletHeader step={step} onBack={() => setStep(step === "settings" || step === "help" ? "welcome" : "welcome")} onSettings={() => setStep("settings")} onHelp={() => setStep("help")} />}
        <div aria-live="polite" className="min-h-[672px]">
          {step === "splash" && <Splash />}
          {step === "welcome" && <Welcome onStart={() => setStep("method")} onHelp={() => setStep("help")} />}
          {step === "method" && <Method onSign={() => setStep("connecting")} onText={() => setStep("text")} />}
          {step === "text" && <TextMessage onSend={() => setStep("sent")} />}
          {step === "connecting" && <Connecting onContinue={() => setStep("permission")} />}
          {step === "permission" && <Permission onAllow={() => setStep("ready")} onCancel={() => setStep("method")} />}
          {step === "ready" && <Ready onStart={() => setStep("live")} onCancel={() => setStep("method")} />}
          {step === "live" && <LiveCamera onPause={() => setStep("translating")} onRetry={() => setStep("uncertain")} onEnd={() => setStep("complete")} />}
          {step === "translating" && <Translating onDone={() => setStep("confirm")} />}
          {step === "confirm" && <Confirm onSend={() => setStep("sent")} onRetry={() => setStep("ready")} />}
          {step === "sent" && <Sent onContinue={() => setStep("conversation")} />}
          {step === "conversation" && <Conversation onSign={() => setStep("live")} onResponse={() => setStep("response")} onEnd={() => setStep("complete")} />}
          {step === "response" && <StaffResponse onContinue={() => setStep("conversation")} />}
          {step === "uncertain" && <Uncertain onRetry={() => setStep("ready")} onContinue={() => setStep("confirm")} />}
          {step === "offline" && <Offline onRetry={() => setStep("connecting")} onEnd={() => setStep("complete")} />}
          {step === "complete" && <Complete onNew={() => setStep("method")} onHome={() => setStep("welcome")} />}
          {step === "settings" && <AccessibilitySettings largeText={largeText} setLargeText={setLargeText} />}
          {step === "help" && <Help />}
        </div>
        <button onClick={() => setStep("offline")} className="absolute bottom-2 right-3 text-[10px] font-bold text-muted-foreground underline focus-visible:ring-2 focus-visible:ring-ring">Preview offline state</button>
      </div>
    </section>
  );
}

function TabletHeader({ step, onBack, onSettings, onHelp }: { step: Step; onBack: () => void; onSettings: () => void; onHelp: () => void }) {
  return <header className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2 border-b border-border bg-card px-3 py-3 sm:px-6">
    <Button variant="ghost" size="icon" aria-label="Go back" onClick={onBack}><ArrowLeft /></Button>
    <div className="min-w-0 text-center"><p className="truncate font-display text-lg font-extrabold">Kenyatta National Hospital</p><p className="text-xs font-semibold text-muted-foreground">Powered by Signova</p></div>
    <div className="flex"><Button variant="ghost" size="icon" aria-label="Accessibility settings" onClick={onSettings}><Accessibility /></Button><Button variant="ghost" size="icon" aria-label="Help" onClick={onHelp}><CircleHelp /></Button></div>
  </header>;
}

function Splash() { return <div className="grid min-h-[720px] place-items-center bg-primary px-8 text-center text-primary-foreground"><div><div className="mx-auto mb-6 grid size-24 place-items-center rounded-3xl bg-accent text-primary"><Hand className="size-12" /></div><h1 className="text-5xl font-extrabold">Signova</h1><p className="mt-4 text-xl font-semibold">Communication without barriers.</p><div className="mx-auto mt-12 flex w-fit gap-2" aria-label="Loading"><span className="size-3 rounded-full bg-accent soft-pulse"/><span className="size-3 rounded-full bg-accent soft-pulse [animation-delay:200ms]"/><span className="size-3 rounded-full bg-accent soft-pulse [animation-delay:400ms]"/></div></div></div>; }

function Welcome({ onStart, onHelp }: { onStart: () => void; onHelp: () => void }) { return <div className="grid min-h-[672px] content-center px-6 py-10 text-center sm:px-16"><div className="mx-auto mb-6 grid size-24 place-items-center rounded-2xl bg-primary text-primary-foreground"><span className="font-display text-3xl font-extrabold">KNH</span></div><p className="mb-2 font-bold uppercase text-primary">Welcome</p><h1 className="mx-auto max-w-2xl text-4xl font-extrabold sm:text-5xl">Welcome to Kenyatta National Hospital</h1><p className="mt-5 text-xl text-muted-foreground">Communication support is available in sign language or text.</p><div className="mx-auto mt-10 grid w-full max-w-xl gap-3"><Button size="touch" onClick={onStart}>Start communication <ChevronRight /></Button><Button size="lg" variant="outline" onClick={onHelp}><Accessibility /> Accessibility help</Button></div></div>; }

function Method({ onSign, onText }: { onSign: () => void; onText: () => void }) { return <div className="px-5 py-10 sm:px-12"><h1 className="text-center text-3xl font-extrabold sm:text-4xl">How would you like to communicate?</h1><p className="mt-3 text-center text-lg text-muted-foreground">Choose the option that feels best for you.</p><div className="mx-auto mt-10 grid max-w-4xl gap-5 sm:grid-cols-2"><button onClick={onSign} className="min-h-72 rounded-2xl border-4 border-primary bg-primary p-8 text-left text-primary-foreground shadow-lg transition-transform active:scale-[.98] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring/40"><span className="mb-12 grid size-20 place-items-center rounded-2xl bg-accent text-primary"><Hand className="size-10" /></span><span className="block font-display text-3xl font-extrabold">Sign language</span><span className="mt-3 block text-lg">Use sign language through the camera.</span></button><button onClick={onText} className="min-h-72 rounded-2xl border-2 border-border bg-card p-8 text-left shadow-sm transition-transform active:scale-[.98] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring/40"><span className="mb-12 grid size-20 place-items-center rounded-2xl bg-accent text-primary"><Keyboard className="size-10" /></span><span className="block font-display text-3xl font-extrabold">Text</span><span className="mt-3 block text-lg text-muted-foreground">Type your message on screen.</span></button></div></div>; }

function Connecting({ onContinue }: { onContinue: () => void }) { return <div className="grid min-h-[640px] place-items-center px-6 text-center"><div><div className="relative mx-auto mb-10 size-32"><span className="absolute inset-0 rounded-full border-4 border-primary/20 soft-pulse"/><span className="absolute inset-4 grid place-items-center rounded-full bg-primary text-primary-foreground"><UserRound className="size-12" /></span></div><h1 className="text-4xl font-extrabold">Connecting you to a staff member</h1><p className="mt-5 text-xl"><span className="text-muted-foreground">Service:</span> <strong>Customer Support</strong></p><div className="mx-auto mt-8 max-w-lg rounded-xl bg-accent p-5 text-left"><p className="flex items-center gap-3 text-lg font-bold"><Clock3 className="text-primary"/> Finding an available staff member...</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-border"><div className="h-full w-2/3 rounded-full bg-primary"/></div></div><Button className="mt-8" size="lg" onClick={onContinue}>Staff found · Connect now <ChevronRight /></Button></div></div>; }

function Permission({ onAllow, onCancel }: { onAllow: () => void; onCancel: () => void }) { return <CenteredIcon icon={<Camera className="size-12"/>} title="Signova needs camera access" body="We use your camera only to recognise sign language during your communication session."><div className="mt-8 grid gap-3"><Button size="touch" onClick={onAllow}><Camera /> Allow camera</Button><Button size="lg" variant="ghost" onClick={onCancel}>Not now</Button></div><p className="mt-6 flex justify-center gap-2 text-sm text-muted-foreground"><ShieldCheck className="size-5 text-primary"/> Your video is private and session-only.</p></CenteredIcon>; }

function Ready({ onStart, onCancel }: { onStart: () => void; onCancel: () => void }) { return <div className="px-4 py-5 sm:px-8"><div className="mb-5 text-center"><h1 className="text-3xl font-extrabold">You’re ready to communicate</h1><p className="mt-2 text-lg text-muted-foreground">Position your hands inside the camera frame.</p></div><CameraFrame ready/><div className="mx-auto mt-5 flex max-w-xl gap-3"><Button className="flex-1" size="touch" onClick={onStart}><Play /> Start signing</Button><Button size="touch" variant="outline" onClick={onCancel}><X/> <span className="hidden sm:inline">Cancel</span></Button></div></div>; }

function CameraFrame({ ready = false }: { ready?: boolean }) { return <div className="relative mx-auto aspect-[4/3] max-h-[460px] overflow-hidden rounded-2xl bg-foreground"><img src={signingImage} alt="A confident Kenyan Deaf woman signing at a hospital service counter" width={1536} height={1024} className="size-full object-cover"/><div className="pointer-events-none absolute inset-[8%] rounded-2xl border-2 border-primary-foreground/80"><span className="absolute -top-1 -left-1 size-8 border-l-4 border-t-4 border-accent"/><span className="absolute -top-1 -right-1 size-8 border-r-4 border-t-4 border-accent"/><span className="absolute -bottom-1 -left-1 size-8 border-b-4 border-l-4 border-accent"/><span className="absolute -bottom-1 -right-1 size-8 border-b-4 border-r-4 border-accent"/></div>{ready && <span className="absolute bottom-4 left-1/2 -translate-x-1/2 rounded-full bg-foreground/80 px-4 py-2 text-sm font-bold text-primary-foreground">Keep both hands visible</span>}</div>; }

function LiveCamera({ onPause, onRetry, onEnd }: { onPause: () => void; onRetry: () => void; onEnd: () => void }) { return <div className="p-3 sm:p-5"><div className="relative"><CameraFrame/><div className="absolute left-4 top-4 rounded-lg bg-foreground/80 px-4 py-3 text-primary-foreground"><p className="flex items-center gap-2 font-bold"><span className="size-2 rounded-full bg-chart-2 soft-pulse"/> Signova is recognising...</p><p className="mt-1 flex items-center gap-2 text-sm"><Check className="size-4 text-chart-2"/> Hands detected</p></div></div><div className="mt-3 rounded-xl bg-accent p-4 sm:p-5"><p className="text-xs font-extrabold uppercase text-primary">Translated message</p><p className="mt-1 text-xl font-bold sm:text-2xl">“Hello, I need help with my account.”</p></div><div className="mt-3 grid grid-cols-3 gap-2"><Button size="lg" onClick={onPause}><Pause/> Pause</Button><Button size="lg" variant="outline" onClick={onRetry}><RotateCcw/> Retry</Button><Button size="lg" variant="ghost" onClick={onEnd}><X/> End</Button></div></div>; }

function Translating({ onDone }: { onDone: () => void }) { return <CenteredIcon icon={<Sparkles className="size-12"/>} title="Translating your sign..." body="Keep your hands still for a moment."><div className="mx-auto mt-8 h-3 max-w-md overflow-hidden rounded-full bg-border"><div className="h-full w-4/5 rounded-full bg-primary"/></div><Button className="mt-8" size="lg" onClick={onDone}><Check/> Translation complete</Button></CenteredIcon>; }
function Confirm({ onSend, onRetry }: { onSend: () => void; onRetry: () => void }) { return <MessageReview eyebrow="We understood:" message="Hello, I need help with my account."><Button size="touch" className="flex-1" onClick={onSend}><Send/> Send</Button><Button size="touch" variant="outline" onClick={onRetry}><RotateCcw/> Try again</Button><Button size="touch" variant="ghost"><Keyboard/> Edit</Button></MessageReview>; }
function Sent({ onContinue }: { onContinue: () => void }) { return <CenteredIcon icon={<Check className="size-12"/>} title="Message sent" body="“Hello, I need help with my account.”"><Button className="mt-9" size="touch" onClick={onContinue}>View conversation <ChevronRight/></Button></CenteredIcon>; }

function Conversation({ onSign, onResponse, onEnd }: { onSign: () => void; onResponse: () => void; onEnd: () => void }) { return <div className="flex min-h-[670px] flex-col"><div className="border-b border-border px-5 py-3"><p className="flex items-center gap-2 font-bold"><span className="size-3 rounded-full bg-chart-2"/> Connected with Grace W.</p><p className="text-sm text-muted-foreground">Customer Support</p></div><div className="flex-1 space-y-4 bg-secondary/45 p-4 sm:p-7"><ConversationCard who="You" time="9:43" text="Hello, I need help with my account." yours/><ConversationCard who="Staff · Grace" time="9:43" text="Of course. How can I help you today?"/><ConversationCard who="You" time="9:44" text="I cannot access my online account." yours/></div><div className="grid grid-cols-[1fr_auto] gap-3 border-t border-border bg-card p-4"><Button size="touch" onClick={onSign}><Hand/> Sign a response</Button><Button size="touch" variant="outline" aria-label="Preview incoming staff response" onClick={onResponse}><MessageSquare/></Button><Button className="col-span-2" variant="ghost" onClick={onEnd}>End session</Button></div></div>; }
function ConversationCard({ who, time, text, yours = false }: { who: string; time: string; text: string; yours?: boolean }) { return <article className={`max-w-2xl rounded-xl border-l-4 p-5 shadow-sm ${yours ? "ml-auto border-primary bg-card" : "border-chart-2 bg-accent"}`}><div className="flex justify-between gap-4"><h2 className="text-sm font-extrabold uppercase text-primary">{who}</h2><time className="text-sm text-muted-foreground">{time}</time></div><p className="mt-2 text-xl font-semibold">{text}</p></article>; }
function StaffResponse({ onContinue }: { onContinue: () => void }) { return <div className="grid min-h-[660px] content-center px-6 sm:px-14"><div className="mx-auto w-full max-w-3xl rounded-2xl border-l-8 border-chart-2 bg-accent p-8 sm:p-12"><div className="mb-6 flex items-center gap-4"><img src={staffImage} alt="Grace, the customer support staff member" loading="lazy" width={1024} height={1024} className="size-16 rounded-full object-cover"/><div><p className="font-extrabold uppercase text-primary">Staff response</p><p className="text-muted-foreground">Grace · Customer Support</p></div></div><p className="text-3xl font-bold leading-snug sm:text-4xl">“Please wait while I check your account.”</p></div><div className="mx-auto mt-7 grid w-full max-w-3xl grid-cols-3 gap-3"><Button variant="outline" size="lg"><Volume2/> Replay</Button><Button variant="outline" size="lg"><Type/> Text size</Button><Button size="lg" onClick={onContinue}>Continue <ChevronRight/></Button></div></div>; }
function Uncertain({ onRetry, onContinue }: { onRetry: () => void; onContinue: () => void }) { return <MessageReview eyebrow="We’re not completely sure about this sign." message="I need..."><div className="mb-4 flex items-center gap-2 rounded-lg bg-secondary p-3 text-sm font-semibold"><AlertTriangle className="text-chart-4"/> Please check the message before sending.</div><Button size="touch" className="flex-1" onClick={onRetry}><RotateCcw/> Try again</Button><Button size="touch" variant="outline"><Keyboard/> Edit</Button><Button size="touch" variant="ghost" onClick={onContinue}>Continue</Button></MessageReview>; }
function Offline({ onRetry, onEnd }: { onRetry: () => void; onEnd: () => void }) { return <CenteredIcon icon={<WifiOff className="size-12"/>} title="Connection interrupted" body="We’re having trouble connecting to the service. Your message is safe."><div className="mt-8 grid gap-3"><Button size="touch" onClick={onRetry}><RefreshCw/> Try again</Button><Button size="lg" variant="ghost" onClick={onEnd}>End session</Button></div></CenteredIcon>; }
function Complete({ onNew, onHome }: { onNew: () => void; onHome: () => void }) { return <CenteredIcon icon={<Check className="size-12"/>} title="Communication complete" body="Thank you for using Kenyatta National Hospital’s communication service."><div className="mt-9 grid gap-3"><Button size="touch" onClick={onNew}>Start new conversation</Button><Button size="lg" variant="outline" onClick={onHome}>Return home</Button></div></CenteredIcon>; }

function TextMessage({ onSend }: { onSend: () => void }) { return <div className="mx-auto max-w-3xl px-5 py-10"><h1 className="text-3xl font-extrabold">Type your message</h1><p className="mt-2 text-lg text-muted-foreground">A staff member will read your message.</p><label htmlFor="deaf-message" className="mt-8 block font-bold">Your message</label><textarea id="deaf-message" className="mt-2 min-h-60 w-full rounded-xl border-2 border-input bg-card p-5 text-xl focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring/30" defaultValue="Hello, I need help with my account."/><Button className="mt-5 w-full" size="touch" onClick={onSend}><Send/> Send message</Button></div>; }
function AccessibilitySettings({ largeText, setLargeText }: { largeText: boolean; setLargeText: (value: boolean) => void }) { const items = [["Large text", "Make words larger across Signova", largeText, setLargeText], ["High contrast", "Increase the difference between colours", false, () => {}], ["Captions", "Show text for every spoken response", true, () => {}], ["Visual notifications", "Use clear on-screen alerts", true, () => {}], ["Reduce motion", "Limit movement and animation", false, () => {}]] as const; return <div className="mx-auto max-w-3xl px-5 py-7"><h1 className="text-3xl font-extrabold">Accessibility settings</h1><p className="mt-2 text-muted-foreground">Choose how Signova works best for you.</p><div className="mt-7 divide-y divide-border rounded-xl border border-border bg-card">{items.map(([label,desc,checked,change]) => <label key={label} className="grid min-h-20 grid-cols-[minmax(0,1fr)_auto] items-center gap-4 p-4"><span><span className="block text-lg font-bold">{label}</span><span className="block text-sm text-muted-foreground">{desc}</span></span><Switch className="h-7 w-12 data-[state=checked]:bg-primary" checked={checked} onCheckedChange={change} aria-label={label}/></label>)}</div><button className="mt-4 flex min-h-16 w-full items-center justify-between rounded-xl border border-border bg-card px-5 text-left font-bold"><span>Language <small className="ml-2 font-normal text-muted-foreground">English</small></span><ChevronRight/></button></div>; }
function Help() { const cards = [[Hand,"How Signova works"],[Play,"How to sign"],[Camera,"Camera help"],[MessageSquare,"Communication help"],[Accessibility,"Accessibility"],[Phone,"Contact staff"]] as const; return <div className="px-5 py-7 sm:px-8"><h1 className="text-3xl font-extrabold">How can we help?</h1><p className="mt-2 text-muted-foreground">Choose a topic for simple visual guidance.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{cards.map(([Icon,label]) => <button key={label} className="flex min-h-28 items-center gap-5 rounded-xl border border-border bg-card p-5 text-left text-lg font-bold shadow-sm focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring/30"><span className="grid size-14 shrink-0 place-items-center rounded-xl bg-accent text-primary"><Icon/></span><span>{label}</span><ChevronRight className="ml-auto text-muted-foreground"/></button>)}</div></div>; }
function CenteredIcon({ icon, title, body, children }: { icon: React.ReactNode; title: string; body: string; children: React.ReactNode }) { return <div className="grid min-h-[650px] place-items-center px-6 text-center"><div className="max-w-2xl"><div className="mx-auto mb-7 grid size-24 place-items-center rounded-full bg-accent text-primary">{icon}</div><h1 className="text-4xl font-extrabold sm:text-5xl">{title}</h1><p className="mx-auto mt-5 max-w-xl text-xl text-muted-foreground">{body}</p>{children}</div></div>; }
function MessageReview({ eyebrow, message, children }: { eyebrow: string; message: string; children: React.ReactNode }) { return <div className="grid min-h-[650px] content-center px-5 sm:px-12"><div className="mx-auto w-full max-w-3xl"><p className="text-lg font-extrabold text-primary">{eyebrow}</p><div className="mt-4 rounded-2xl border-2 border-primary/20 bg-accent p-7 sm:p-10"><p className="text-3xl font-bold leading-snug sm:text-4xl">“{message}”</p></div><div className="mt-6 flex flex-wrap gap-3">{children}</div></div></div>; }

function StaffDashboard() {
  const [accepted, setAccepted] = useState(false);
  const [reply, setReply] = useState("Please wait while I check your account.");
  return <section className="mx-auto max-w-[1500px] px-4 py-6 sm:px-7"><header className="grid grid-cols-[minmax(0,1fr)_auto] items-center gap-4"><div className="min-w-0"><p className="font-bold text-primary">Kenyatta National Hospital</p><h1 className="truncate text-3xl font-extrabold">Communication desk</h1></div><div className="flex items-center gap-3"><span className="hidden rounded-full bg-accent px-4 py-2 text-sm font-bold sm:block">● Available</span><img src={staffImage} alt="Grace Wanjiku" loading="lazy" width={1024} height={1024} className="size-12 rounded-full object-cover"/></div></header>
    {!accepted ? <div className="mt-8 grid gap-6 lg:grid-cols-[1fr_340px]"><div><h2 className="text-xl font-extrabold">Incoming requests</h2><article className="mt-4 grid gap-5 rounded-xl border-l-4 border-primary bg-card p-6 shadow-sm sm:grid-cols-[auto_1fr_auto] sm:items-center"><span className="grid size-16 place-items-center rounded-full bg-accent text-primary"><Hand/></span><div><p className="font-extrabold">Sign language request</p><p className="mt-1 text-muted-foreground">Customer Support · Counter tablet 04</p><p className="mt-2 text-sm font-bold text-primary">Waiting 00:18</p></div><Button size="lg" onClick={() => setAccepted(true)}>Accept session</Button></article></div><aside className="rounded-xl bg-primary p-6 text-primary-foreground"><h2 className="text-xl font-extrabold">Today</h2><p className="mt-8 text-5xl font-extrabold">12</p><p>completed conversations</p><div className="mt-8 border-t border-primary-foreground/30 pt-5"><p className="text-sm">Average wait time</p><p className="mt-1 text-2xl font-bold">34 seconds</p></div></aside></div> : <ActiveStaff reply={reply} setReply={setReply} onEnd={() => setAccepted(false)} />}
  </section>;
}
function ActiveStaff({ reply, setReply, onEnd }: { reply: string; setReply: (value: string) => void; onEnd: () => void }) { return <div className="mt-6 grid min-h-[700px] gap-4 lg:grid-cols-[250px_minmax(380px,1fr)_280px]"><aside className="rounded-xl border border-border bg-card p-5"><p className="text-xs font-extrabold uppercase text-primary">Active session</p><h2 className="mt-2 text-xl font-extrabold">Counter tablet 04</h2><dl className="mt-6 space-y-5 text-sm"><div><dt className="text-muted-foreground">Service</dt><dd className="font-bold">Customer Support</dd></div><div><dt className="text-muted-foreground">Method</dt><dd className="font-bold">Kenyan Sign Language</dd></div><div><dt className="text-muted-foreground">Duration</dt><dd className="font-bold">04:32</dd></div></dl><Button className="mt-8 w-full" variant="outline" onClick={onEnd}>End session</Button><Button className="mt-2 w-full" variant="ghost"><History/> History</Button></aside><section className="flex flex-col rounded-xl border border-border bg-card"><div className="border-b border-border p-5"><h2 className="text-xl font-extrabold">Live conversation</h2><p className="text-sm text-muted-foreground">All spoken responses are shown as text.</p></div><div className="flex-1 space-y-4 bg-secondary/45 p-5"><ConversationCard who="Deaf user · Translated" time="9:43" text="Hello, I need help with my account."/><ConversationCard who="You" time="9:43" text="Of course. How can I help you today?" yours/><ConversationCard who="Deaf user · Translated" time="9:44" text="I cannot access my online account."/></div><div className="border-t border-border p-4"><label htmlFor="staff-reply" className="font-bold">Your response</label><textarea id="staff-reply" value={reply} onChange={e => setReply(e.target.value)} className="mt-2 min-h-24 w-full rounded-lg border border-input bg-background p-3 focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-ring/30"/><div className="mt-3 flex gap-2"><Button className="flex-1"><Send/> Send text</Button><Button variant="outline"><Mic/> Speak</Button></div></div></section><aside className="space-y-4"><div className="rounded-xl border border-border bg-card p-5"><h2 className="font-extrabold">Translation status</h2><p className="mt-4 flex items-center gap-2 text-sm font-bold"><Check className="text-chart-2"/> Hands detected</p><p className="mt-3 flex items-center gap-2 text-sm font-bold"><Check className="text-chart-2"/> Translation complete</p><div className="mt-5 rounded-lg bg-accent p-4"><p className="text-xs font-bold uppercase text-primary">Confidence</p><p className="mt-1 text-2xl font-extrabold">94%</p></div></div><div className="rounded-xl border border-border bg-card p-5"><h2 className="font-extrabold">Privacy</h2><p className="mt-3 text-sm text-muted-foreground">Camera active only for this session. Video is not stored.</p></div></aside></div>; }

function AdminPortal() {
  const [section, setSection] = useState("Branding"); const [org, setOrg] = useState("Kenyatta National Hospital"); const [message, setMessage] = useState("Communication support is available.");
  const nav = [[LayoutDashboard,"Overview"],[Users,"Staff"],[SlidersHorizontal,"Services"],[Building2,"Organisation"],[Palette,"Branding"],[MonitorUp,"Analytics"],[Accessibility,"Accessibility"],[Lock,"Security"],[Settings,"Settings"]] as const;
  return <section className="mx-auto grid min-h-[calc(100dvh-65px)] max-w-[1500px] md:grid-cols-[220px_1fr]"><aside className="border-r border-border bg-card p-3 md:p-5"><p className="mb-4 hidden text-xs font-extrabold uppercase text-muted-foreground md:block">Organisation portal</p><nav aria-label="Admin sections" className="flex gap-2 overflow-x-auto md:block md:space-y-1">{nav.map(([Icon,label]) => <button key={label} onClick={() => setSection(label)} className={`flex min-h-11 shrink-0 items-center gap-3 rounded-lg px-3 text-sm font-bold md:w-full ${section === label ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted"}`}><Icon className="size-5"/>{label}</button>)}</nav></aside><div className="min-w-0 p-4 sm:p-7"><header><p className="font-bold text-primary">Kenyatta National Hospital</p><h1 className="text-3xl font-extrabold">{section === "Branding" ? "White-label branding" : section}</h1><p className="mt-1 text-muted-foreground">{section === "Branding" ? "Shape the welcome experience shown at every service counter." : `Manage ${section.toLowerCase()} for your organisation.`}</p></header>{section === "Branding" ? <div className="mt-7 grid gap-8 xl:grid-cols-[minmax(320px,440px)_1fr]"><form className="space-y-5 rounded-xl border border-border bg-card p-6" onSubmit={e => e.preventDefault()}><h2 className="text-xl font-extrabold">Organisation identity</h2><label className="block"><span className="font-bold">Organisation logo</span><span className="mt-2 flex min-h-20 items-center gap-4 rounded-lg border-2 border-dashed border-input p-4"><span className="grid size-14 place-items-center rounded-lg bg-primary font-bold text-primary-foreground">KNH</span><span className="text-sm text-muted-foreground">Select a PNG or SVG logo</span></span></label><Field label="Organisation name" value={org} setValue={setOrg}/><Field label="Welcome message" value={message} setValue={setMessage}/><div className="grid grid-cols-2 gap-4"><label className="font-bold">Primary colour<span className="mt-2 flex h-12 items-center gap-2 rounded-lg border border-input px-3"><span className="size-7 rounded-md bg-primary"/> Royal Purple</span></label><label className="font-bold">Background<span className="mt-2 flex h-12 items-center gap-2 rounded-lg border border-input px-3"><span className="size-7 rounded-md bg-accent"/> Cornsilk</span></label></div><Field label="Service information" value="Customer Support · Main Reception" setValue={() => {}}/><Button className="w-full" size="lg">Save branding</Button></form><TabletPreview org={org} message={message}/></div> : <AdminPlaceholder section={section}/>}</div></section>;
}
function Field({ label, value, setValue }: { label: string; value: string; setValue: (value: string) => void }) { const id = `field-${label.toLowerCase().replaceAll(' ','-')}`; return <label htmlFor={id} className="block font-bold">{label}<Input id={id} className="mt-2 h-12" value={value} onChange={e => setValue(e.target.value)}/></label>; }
function TabletPreview({ org, message }: { org: string; message: string }) { return <div><div className="mb-3 flex items-center justify-between"><h2 className="text-xl font-extrabold">Live tablet preview</h2><span className="rounded-full bg-accent px-3 py-1 text-xs font-bold text-primary">Live</span></div><div className="mx-auto max-w-2xl rounded-[1.5rem] border-[9px] border-foreground bg-background shadow-xl"><div className="h-6 bg-foreground"/><div className="min-h-[540px] p-8 text-center"><div className="mx-auto mt-12 grid size-20 place-items-center rounded-xl bg-primary text-xl font-extrabold text-primary-foreground">KNH</div><p className="mt-7 font-bold uppercase text-primary">Welcome</p><h3 className="mx-auto mt-2 max-w-lg text-3xl font-extrabold">Welcome to {org || "Your organisation"}</h3><p className="mt-4 text-lg text-muted-foreground">{message || "Communication support is available."}</p><Button className="mt-10 w-full" size="touch">Start communication <ChevronRight/></Button><Button className="mt-3 w-full" variant="outline" size="lg"><Accessibility/> Accessibility help</Button></div></div></div>; }
function AdminPlaceholder({ section }: { section: string }) { return <div className="mt-7 grid gap-5 sm:grid-cols-3"><article className="rounded-xl border border-border bg-card p-6 sm:col-span-2"><h2 className="text-xl font-extrabold">{section} overview</h2><p className="mt-3 text-muted-foreground">Clear organisation controls and accessible defaults are ready for your team.</p><div className="mt-8 grid grid-cols-2 gap-4"><div className="rounded-lg bg-accent p-5"><p className="text-3xl font-extrabold text-primary">24</p><p className="font-bold">Active staff</p></div><div className="rounded-lg bg-muted p-5"><p className="text-3xl font-extrabold">6</p><p className="font-bold">Services</p></div></div></article><article className="rounded-xl bg-primary p-6 text-primary-foreground"><ShieldCheck className="size-9"/><h2 className="mt-5 text-xl font-extrabold">System healthy</h2><p className="mt-2 text-sm">All service counters are connected and accessibility settings are active.</p></article></div>; }